### ISSUE TITLE
Can't read proximity sensor values

### ISSUE THREAD

**Issue by carlos0202** [aritchie/sensors#1]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible
Contact GitHub

**Comment by aritchie** [comment]
Fill out the form with some sort of details 
* code example of HOW you are using it, 
* did you check if the sensor was even available (IsAvailable property)?
* what platform(s) that is giving you the problem
* any exception?

I don't think this is too much to ask
