### ISSUE TITLE
Android Pedometer service on background/killed

### ISSUE THREAD

**Issue by darrencl** [aritchie/sensors#13]
Hi, I am trying to use this library to get user's steps counter data from the sensor. I am just wondering if I start to use the library, can the pedometer service capture the steps when the app runs in background/killed?

Also, from the 'how to use basics' section, to subscribe on sensor's activity, I need to use `.subscribe()` method and using the lambda to catch `reading` variable like below.

`CrossSensors.Pedometer.WhenReadingTaken().Subscribe(reading => {});`

What kind of object is `reading`? I could not seem to get any properties, etc. from that object. Do I need that object to check on steps changes?

Any help would be appreciated.

Cheers!

**Comment by aritchie** [comment]
This library doesn't do anything to keep your app alive.  You need to install an android service to do this.  

The pedometer sensor returns an integer.  On iOS, it fires for each step (mostly).   Android usually returns every 4-5 steps.

Please note that this isn't a support channel.  I would encourage you to look through the codebase yourself and get a thorough understanding of reactive extensions before using this further.
