### ISSUE TITLE
how to change delay of proximity sensor?

### ISSUE THREAD

**Issue by EmilAlipiev** [aritchie/sensors#2]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
1.0.1

 Thanks for another great plugin :) I only want to ask you 2 newbie questions. 
1) Is it possible to adjust delay? I looked through your code and if I understand correctly, it looks like hardcoded, does it?
`public TimeSpan ReportInterval { get; set; } = TimeSpan.FromMilliseconds(500);`

2) WhenReadingTaken is only fired if it is true. I am not good at native android implementation but as I read the google docs. it is supposed to return when onSensorChanged. It is still fine for only true case but when It is fired true, It hits 4-5 times if I implement as below. Am I supposed to expect only 1 time or multiple hits are correct behavior? 
```
int count=0;
 if (sensor != null && sensor.IsAvailable && sensorSub == null)
            {
                sensorSub = sensor.WhenReadingTaken().Subscribe(reading =>
                {
                    if (reading == true)
                    {
                        count += 1;
                        lblCounterText = count.ToString();
                    }
                });
            }
```

**Comment by aritchie** [comment]
1) The places where you are seeing the report interval are just left over junk that I don't plan on using.  The reasoning is that you can Buffer (get X results for a time period) or Sample (get a single result every X time period). 

2) You will get multiple hits for all sensors because it is an event stream.  If you only want 1 reading, use .Take(1) before you subscribe.

**Comment by EmilAlipiev** [comment]
1) Ok, I am bit confused now. Because when I look at the AbstractSensor implementation, It looks to me that ReportInterval is used if this code is not in active.

```
		public TimeSpan ReportInterval { get; set; } = TimeSpan.FromMilliseconds(500);



        IObservable<T> readOb;
        public IObservable<T> WhenReadingTaken()
        {
            this.readOb = this.readOb ?? Observable.Create<T>(ob =>
            {
				var mgr = new AcrSensorManager(this.sensorManager);
                var delay = this.ToSensorDelay(this.ReportInterval);

                mgr.Start(this.type, delay, e =>
                {
                    var reading = this.ToReading(e);
                    ob.OnNext(reading);
                });
                return () => mgr.Stop();
            })
            .Publish()
            .RefCount();

            return this.readOb;
        }


        protected SensorDelay ToSensorDelay(TimeSpan timeSpan)
        {
            if (timeSpan.TotalMilliseconds <= 100)
                return SensorDelay.Fastest;

            if (timeSpan.TotalMilliseconds <= 250)
                return SensorDelay.Game;

            if (timeSpan.TotalMilliseconds <= 500)
                return SensorDelay.Ui;

           return SensorDelay.Normal;
        }
```

2) When using take(1) it will only return 1 time and stop returning. For example, a pushup counter example is a good one. When my face come closer to the phone screen or touches, it fires true more than 1 time because of I think that it is handled like below in Java. You just use values[0] to ignore others but in your plugin, for each value, it is fired true (usually 4-5 times), next pushup again 4-5times. If I do take(1), it accepts first pushup but then stops returning for other attempts. This is probably quite specific implementation but what I wanted to say that, is it maybe not better idea to return values instead bool(true)? So user can handle it whatever his purpose. 

```
@Override
	public void onSensorChanged(SensorEvent event) {		
		int val = (int) event.values[0];
		
		if (val > 1)
			val = 1;
		
		count += val;
		
		tvCounter.setText(
			String.valueOf(
				count));
	}
	
```
Source: https://github.com/SPython/pushup-counter/blob/master/src/com/spython/PushUpCounter/CounterActivity.java

**Comment by aritchie** [comment]
Listen man... no offence, but I don't have time to debate every answer I give.  You are welcome to submit PR's or take the library as is...

1) The code is running, but the report interval was something I changed direction with during development.  As I said, it was not designed to be in use.  Use Sample or Buffer from the observable if the rate is coming in too fast.  Android should be returning at the fastest rate available underneath the hood.  That is the only thing that truly needs to be corrected here.

2) You are only seeing this from the perspective of android.  If I return all of the values, android will be the only platform that has it.  iOS only returns a boolean and UWP is all kinds of weird that I didn't bother to tackle for now.  Again, if this isn't doing what you think it should, feel free to submit a PR.

**Comment by EmilAlipiev** [comment]
2) you are absolutely right. I didnt think about IOS and UWP. actually I expressed myself wrong I wanted to say that it could be something like this below. So result is still bool. I will submit a PR request after testing this on Android

   ```
protected override bool ToReading(SensorEvent e)
        {          

         if (e.Values[0] < e.Sensor.MaximumRange)
            {
                // Detected something nearby
                return true;
            }
            else
            {
                // Nothing is nearby
                return false;
            }
      
        }
```
