### ISSUE TITLE
Error when installing from nuget

### ISSUE THREAD

**Issue by navirius** [aritchie/sensors#4]
when installing this library from nuget for PCL project it give me an error

Error |   | Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by aritchie** [comment]
This library uses .net standard 1.0 which supports PCL Profile 259.  Please use the issue template in the future if you expect any sort of answer.
