### ISSUE TITLE
WhenReadingTaken(), How to break or stop readings?

### ISSUE THREAD

**Issue by thorradin** [aritchie/sensors#5]
CrossSensors.Compass.WhenReadingTaken().Subscribe(reading =>
             {
                 sensorReading= Convert.ToInt32(reading.MagneticHeading);
             });
-----------------------------------------------------------------------------------------
The issue is the following:
How to break; out of the WhenReadingTaken(), the method keeps reading even if I'm outside the view. 
The scenario or the issue: 
All my main code is inside the method above, the main idea is that the device vibrates when you move in the wrong direction which works perfectly but, I can't find a way to break, or stop the readings it will keep reading and vibrating even beyond being in the same view. 

Thank you in advance, the issue is happening on iOS & Android.

**Comment by aritchie** [comment]
I would strongly encourage you to learn reactive extensions before using this library.

To answer your question, keep a reference to your subscription:

var sub = CrossSensors.Sensor.WhenReadingTaken().Subscribe(...);

When you want the sensor to stop taking readings:

sub.Dispose();

**Comment by thorradin** [comment]
Thank you so much, you are the best. And Reactive Extension is so helpful.
