### ISSUE TITLE
[Request] Property for sensor resolution (samplerate) 

### ISSUE THREAD

**Issue by dimitrijevic** [aritchie/sensors#7]
Hi Aritchie,
  I was wondering how many of your supported sensor platforms have in common, so as to add a property to get (or even set) the sample rate of the sensors (in my case UWP accelerometer, but I'm guessing other mobile platforms might have similar options)...

**Comment by aritchie** [comment]
You don’t need it.  Use .Sample(timespan) like I do in the sample project with this project
