### ISSUE TITLE
Proximity sensor on ios

### ISSUE THREAD

**Issue by dbalconi** [aritchie/sensors#9]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard

## Version of OS(s) listed above with issue
10.3 and 11.2.6

## Version of ACR Sensor Plugin Library
latest on nuget -  2.2.1

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Proximity sensors not working on ios , tested in my app and even in original project Xamarin app.
I've download git project, open with xamarin studio (macos) the Sample app  and run on 2 different iphone 6s (11.2.6 and 10.3).
Android is ok.
I didnt tested other platforms 
No log, no output

in my project i've  checked IsAvailable

```
if(CrossSensors.Proximity.IsAvailable){
                Console.WriteLine("YES");
            }else{
                Console.WriteLine("NO");
            }
            
           
            var ProxSubs = CrossSensors.Proximity.WhenReadingTaken().Subscribe(reading => {
                
                Console.WriteLine("Sto leggendo PROSSIMITA uguale a {0}",reading.ToString());

                //DisplayAlert("asddsa",  reading.ToString(), "as");
                if(reading == true){
                    isProxOK = true;
                    checkBothSensors();
                    //StartConnection();
                }else{
                    isProxOK = false;
                }
            });
```

IsAvailable return true, but dont start reading sensor. Dont do the console log either.
Couple lne under there is the same piece of code for axcelerometer, work great.

In andorid both work great. 

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Should be working in 2.4.0.

**Comment by dbalconi** [comment]
Hi @aritchie , 
Now it works great! event more than great ..
Did you know if there is a way to keep screen on when using proximity sensor?
I want to keep screen alive  and do stuff when phone is near an object (proximity) and vertical (accelerometer).
All works and event is fired in both platform (ios,android) , but in ios the screen shut down and prevent showing stuff on screen :(
Did you know if there is a way to prevent this?

I'm doing some platform specific implementation like this 

`public bool ScreenAlwaysOn(bool TurnOnOff = true)
        {
            if (TurnOnOff == true){
                // Disable Auto-Lock
                UIApplication.SharedApplication.IdleTimerDisabled = true;
                UIDevice.CurrentDevice.ProximityMonitoringEnabled = false;
                Console.WriteLine("SCHERMO ACCESO LOCK ON");
            }else{
                UIApplication.SharedApplication.IdleTimerDisabled = false;
                UIDevice.CurrentDevice.ProximityMonitoringEnabled = true;
                Console.WriteLine("SCHERMO ACCESO LOCK OFF");
            }

            return true;
                 
        }`

Did you know a way to keep screen alive?
Thanks a lot

**Comment by aritchie** [comment]
@dbalconi This question is external to this library.  However, I do have a library that does this already (Acr.DeviceInfo).

**Comment by dbalconi** [comment]
Yes i konw, just wondering if you ever encountered same issue and figured out how to solve. I'll take a look at acr.deviceinfo.
Thanks a lot
D
